src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Author
 *
 * @ORM\Table(name="author")
 * @ORM\Entity
 */
class Author
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255, nullable=false)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=255, nullable=false)
     */
    private $lastname;

    /** @var Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Book", mappedBy="author")
     */
    private $books;

    /**
     * Author constructor.
     */
    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    /**
     * @return Collection
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->getFirstname() . " " . $this->getLastname();
    }

    public function __toString()
    {
        return $this->getFullname();
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Entity\Book;
use App\Entity\Category;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DefaultController
 * @package App\Controller
 */
class DefaultController extends BaseController
{

    /**
     * @Route("/", name="homepage")
     */
    public function homepage()
    {
        $books = $this->getDoctrine()->getRepository(Book::class)->findLast(6);
        $categories = $this->getDoctrine()->getRepository(Category::class)->findBy([], ['name' => 'ASC']);
    return $this->render('default/homepage.html.twig', [
        "books" => $books,
        "categories" => $categories
    ]);
    }


}

templates/default/homepage.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <section class="header-home">
        <div class="container">
            <div class="jumbotron">

                <h1>La plateforme n°1 des lecteurs !</h1>

                <p>Booklib est une plateforme vous permettant de visualiser les livres disponibles dans les boîtes à
                    livres autour de chez vous.</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
                    labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores
                    et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
                    labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores
                    et ea rebum.</p>

                <div class="card">
                    <div class="card-header">
                        <h2 class="panel-title text-center">Rechercher un livre</h2>
                    </div>
                    <div class="card-body">
                        <form class="form-inline flex-row justify-content-center">
                            <div class="form-group mr-sm-2">
                                <label class="sr-only" for="inputTitle">Titre</label>
                                <input type="text" class="form-control" id="inputTitle" placeholder="Titre">
                            </div>
                            <div class="form-group mr-sm-2">
                                <label class="sr-only" for="selectCategory">Email</label>
                                <select class="form-control" id="selectCategory">
                                    <option disabled selected>Toutes les catégories</option>
                                    {% for category in categories %}
                                        <option>{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="submit" class="btn btn-default">
                                <i class="fa fa-search"></i>
                                Rechercher
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="container">

        <div class="row">

            <div class="col-md-8 last-books">
                <h2>Les derniers livres</h2>
                <div class="row flex-grow-1">
                    {% for book in books %}
                        <div class="col-sm-6 col-md-4">
                            {% include 'book/card.html.twig' with {'book' : book} only %}
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h2 class="panel-title">Top villes</h2>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">125 livres</span>
                                Nantes
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">113 livres</span>
                                Rennes
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">92 livres</span>
                                Angers
                            </a>
                        </div>
                        <a class="btn btn-primary btn-block" href="#"><i class="fa fa-map"></i> Voir toutes les
                            villes</a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h2 class="panel-title">Top utilisateurs</h2>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">223 échanges</span>
                                Guillaume C.
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">187 échanges</span>
                                Florian C.
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">155 échanges</span>
                                Emilie D.
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">152 échanges</span>
                                Bastien B.
                            </a>
                            <a href="#" class="list-group-item">
                                <span class="badge badge-dark">150 échanges</span>
                                Kevin C.
                            </a>
                        </div>
                        <a class="btn btn-primary btn-block" href="#"><i class="fa fa-users"></i> Voir tous les
                            utilisateurs</a>
                    </div>
                </div>
            </div>

        </div>

    </section>

    <section class="container">

        <h2>Rechercher une boîte à livre</h2>

        <div id="map-books"></div>

    </section>
{% endblock %}

templates/default/index.html.twig
{% extends "base.html.twig" %}

{% block header %}
    {{ parent() }}
    <header>
        HEADER INDEX
    </header>
{% endblock %}

{% block body %}
<div>

    <h1>{{ author.fullname }}</h1>
    <h2>Listes des livres</h2>
    <ul>
        {% for book in  author.books %}

           <li>
               <a href="{{ path('book_show', {'slug': book.slug}) }}">

               {{ book.title }}


               </a>
           </li>

        {% endfor %}
    </ul>

</div>

{% endblock %}